apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cc-githubactions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cc-githubactions 
  name: cc-githubactions
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cc-githubactions 
